fcj

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,49 +1,116 @@
-name: semantic-pull-request
-description: Ensure your PR title matches the Conventional Commits spec (https://www.conventionalcommits.org/).
-runs:
-  using: 'node24'
-  main: 'dist/index.js'
+name: 'Setup asset of Github Releases'
+description: 'GitHub Action for gh-setup'
 branding:
-  icon: 'shield'
-  color: 'green'
+  icon: 'zap'
+  color: 'gray-dark'
 inputs:
-  types:
-    description: "Provide custom types (newline delimited) if you don't want the default ones from https://www.conventionalcommits.org."
+  github-token:
+    description: The GitHub token
+    default: ${{ github.token }}
     required: false
-  scopes:
-    description: 'Configure which scopes are allowed (newline delimited). These are regex patterns auto-wrapped in `^ $`.'
+  repo:
+    description: "Target repository ([HOST/]OWNER/REPO)"
+    required: true
+  version:
+    description: "Release version"
+    default: ""
     required: false
-  requireScope:
-    description: 'Configure that a scope must always be provided.'
+  os:
+    description: "Specify OS of asset"
+    default: ""
     required: false
-  disallowScopes:
-    description: 'Configure which scopes are disallowed in PR titles (newline delimited). These are regex patterns auto-wrapped in ` ^$`.'
+  arch:
+    description: "Specify arch of asset"
+    default: ""
     required: false
-  subjectPattern:
-    description: "Configure additional validation for the subject based on a regex. E.g. '^(?![A-Z]).+$' ensures the subject doesn't start with an uppercase character."
+  match:
+    description: "Regexp to match asset name"
+    default: ""
     required: false
-  subjectPatternError:
-    description: "If `subjectPattern` is configured, you can use this property to override the default error message that is shown when the pattern doesn't match. The variables `subject` and `title` can be used within the message."
+  bin-dir:
+    description: "Executable path"
+    default: ""
     required: false
-  validateSingleCommit:
-    description: 'When using "Squash and merge" on a PR with only one commit, GitHub will suggest using that commit message instead of the PR title for the merge commit, and it''s easy to commit this by mistake. Enable this option to also validate the commit message for one commit PRs.'
+  bin-match:
+    description: "Regexp to match bin path in asset"
+    default: ""
     required: false
-  validateSingleCommitMatchesPrTitle:
-    description: 'Related to `validateSingleCommit` you can opt-in to validate that the PR title matches a single commit to avoid confusion.'
+  checksum:
+    description: "Checksum of asset"
+    default: ""
     required: false
-  githubBaseUrl:
-    description: 'The GitHub base URL will be automatically set to the correct value from the GitHub context variable. If you want to override this, you can do so here (not recommended).'
+  force:
+    description: "Enable force setup"
+    default: ""
     required: false
-    default: '${{ github.api_url }}'
-  ignoreLabels:
-    description: 'If the PR contains one of these labels (newline delimited), the validation is skipped. If you want to rerun the validation when labels change, you might want to use the `labeled` and `unlabeled` event triggers in your workflow.'
+  strict:
+    description: "Require strict match"
+    default: ""
     required: false
-  headerPattern:
-    description: "If you're using a format for the PR title that differs from the traditional Conventional Commits spec, you can use this to customize the parsing of the type, scope and subject. The `headerPattern` should contain a regex where the capturing groups in parentheses correspond to the parts listed in `headerPatternCorrespondence`. For more details see: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser#headerpattern"
+  skip-content-type-check:
+    description: "Skip check content-type of assets"
+    default: ""
     required: false
-  headerPatternCorrespondence:
-    description: 'If `headerPattern` is configured, you can use this to define which capturing groups correspond to the type, scope and subject.'
+  verify-attestation:
+    description: "Enable attestation verification using 'gh attestation verify'"
+    default: ""
     required: false
-  wip:
-    description: "For work-in-progress PRs you can typically use draft pull requests from Github. However, private repositories on the free plan don't have this option and therefore this action allows you to opt-in to using the special '[WIP]' prefix to indicate this state. This will avoid the validation of the PR title and the pull request checks remain pending. Note that a second check will be reported if this is enabled."
+  attestation-flags:
+    description: "Additional flags to pass to 'gh attestation verify'"
+    default: ""
     required: false
+  gh-setup-version:
+    description: "Version of gh-setup"
+    default: "v1.11.6"
+    required: false
+runs:
+  using: "composite"
+  steps:
+    - 
+      name: Subscription check
+      run: |
+        # validate subscription status
+        API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"
+
+        # Set a timeout for the curl command (3 seconds)
+        RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
+        CURL_EXIT_CODE=$?
+
+        # Decide based on curl exit code and HTTP status
+        if [ $CURL_EXIT_CODE -ne 0 ]; then
+          echo "Timeout or API not reachable. Continuing to next step."
+        elif [ "$RESPONSE" = "200" ]; then
+          :
+        elif [ "$RESPONSE" = "403" ]; then
+          echo "Subscription is not valid. Reach out to support@stepsecurity.io"
+          exit 1
+        else
+          echo "Timeout or API not reachable. Continuing to next step."
+        fi
+      shell: bash
+    -
+      id: install-gh-setup
+      run: ${GITHUB_ACTION_PATH}/scripts/install-gh-setup.sh
+      shell: bash
+      env:
+        GH_SETUP_GITHUB_TOKEN: ${{ inputs.github-token }}
+        GH_SETUP_GH_SETUP_VERSION: ${{ inputs.gh-setup-version }}
+    -
+      run: ${GITHUB_ACTION_PATH}/scripts/run-gh-setup.sh
+      shell: bash
+      env:
+        GH_SETUP_GITHUB_TOKEN: ${{ inputs.github-token }}
+        GH_SETUP_REPO: ${{ inputs.repo }}
+        GH_SETUP_VERSION: ${{ inputs.version }}
+        GH_SETUP_OS: ${{ inputs.os }}
+        GH_SETUP_ARCH: ${{ inputs.arch }}
+        GH_SETUP_MATCH: ${{ inputs.match }}
+        GH_SETUP_BIN_DIR: ${{ inputs.bin-dir }}
+        GH_SETUP_BIN_MATCH: ${{ inputs.bin-match }}
+        GH_SETUP_CHECKSUM: ${{ inputs.checksum }}
+        GH_SETUP_FORCE: ${{ inputs.force }}
+        GH_SETUP_STRICT: ${{ inputs.strict }}
+        GH_SETUP_SKIP_CONTENT_TYPE_CHECK: ${{ inputs.skip-content-type-check }}
+        GH_SETUP_VERIFY_ATTESTATION: ${{ inputs.verify-attestation }}
+        GH_SETUP_ATTESTATION_FLAGS: ${{ inputs.attestation-flags }}
+        GH_SETUP_BIN: ${{ steps.install-gh-setup.outputs.bin }}
